name: phone_auth
description: A phone authentication tutorial.

version: 1.4.0+5

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^4.0.1+1
  firebase_auth: ^0.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/glogo.png