name: phone_auth
description: A phone authentication tutorial.

version: 1.3.0+4

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^3.2.4
  firebase_auth: ^0.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/glogo.png